name: Imprimiendo Hola Mundo
run-name: !Estoy aprendiendo Github actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr script
        run: java -jar holaMundo.java
